# Generated by Django 4.1 on 2025-11-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="created_at",),
    ]
