# Generated by Django 4.1 on 2025-12-17 07:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import learning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="知识点名称")),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="learning.knowledgepoint",
                        verbose_name="子知识点",
                    ),
                ),
            ],
            options={"verbose_name": "知识点", "verbose_name_plural": "知识点",},
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="科目名称")),
                ("description", models.TextField(blank=True, verbose_name="科目描述")),
                (
                    "dataset",
                    models.CharField(
                        default="",
                        help_text="对应习题表的模型名称，如：MathExercise, ChineseExercise",
                        max_length=100,
                        verbose_name="关联数据集",
                    ),
                ),
            ],
            options={"verbose_name": "科目", "verbose_name_plural": "科目",},
        ),
        migrations.CreateModel(
            name="StudentDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mastery_level", models.FloatField(default=0.0, verbose_name="掌握程度")),
                (
                    "last_practiced",
                    models.DateTimeField(auto_now=True, verbose_name="最后练习时间"),
                ),
                ("practice_count", models.IntegerField(default=0, verbose_name="练习次数")),
                ("correct_count", models.IntegerField(default=0, verbose_name="正确次数")),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.knowledgepoint",
                        verbose_name="知识点",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={"verbose_name": "学生诊断", "verbose_name_plural": "学生诊断",},
        ),
        migrations.CreateModel(
            name="QMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="关联对象ID"
                    ),
                ),
                ("weight", models.FloatField(default=1.0, verbose_name="权重")),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="关联模型",
                    ),
                ),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.knowledgepoint",
                        verbose_name="知识点",
                    ),
                ),
            ],
            options={"verbose_name": "Q矩阵", "verbose_name_plural": "Q矩阵",},
        ),
        migrations.CreateModel(
            name="MathExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problemsets",
                    models.CharField(default="", max_length=200, verbose_name="习题集ID"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="习题标题")),
                ("content", models.TextField(verbose_name="习题内容")),
                (
                    "question_type",
                    models.CharField(
                        default="single", max_length=10, verbose_name="题型"
                    ),
                ),
                (
                    "option_text",
                    models.CharField(
                        default=None, max_length=1000, verbose_name="选项内容"
                    ),
                ),
                (
                    "answer",
                    models.CharField(default=None, max_length=500, verbose_name="答案"),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[(1, "简单"), (2, "中等"), (3, "困难")], default=2
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="所属科目",
                    ),
                ),
            ],
            options={
                "verbose_name": "数学习题",
                "verbose_name_plural": "数学习题",
                "db_table": "learning_math_exercise",
            },
        ),
        migrations.AddField(
            model_name="knowledgepoint",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.subject",
                verbose_name="所属科目",
            ),
        ),
        migrations.CreateModel(
            name="ExerciseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=learning.models.exercise_file_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "txt",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                        verbose_name="习题文件",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("txt", "文本文件"),
                            ("pdf", "PDF文件"),
                            ("doc", "Word文档"),
                            ("docx", "Word文档"),
                            ("xls", "Excel文件"),
                            ("xlsx", "Excel文件"),
                        ],
                        max_length=10,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("error", "处理失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理完成时间"),
                ),
                (
                    "exercise_count",
                    models.IntegerField(default=0, verbose_name="生成的习题数量"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="所属科目",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "习题文件",
                "verbose_name_plural": "习题文件",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EnglishExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problemsets",
                    models.CharField(default="", max_length=200, verbose_name="习题集ID"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="习题标题")),
                ("content", models.TextField(verbose_name="习题内容")),
                (
                    "question_type",
                    models.CharField(
                        default="single", max_length=10, verbose_name="题型"
                    ),
                ),
                (
                    "option_text",
                    models.CharField(
                        default=None, max_length=1000, verbose_name="选项内容"
                    ),
                ),
                (
                    "answer",
                    models.CharField(default=None, max_length=500, verbose_name="答案"),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[(1, "简单"), (2, "中等"), (3, "困难")], default=2
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="所属科目",
                    ),
                ),
            ],
            options={
                "verbose_name": "英语习题",
                "verbose_name_plural": "英语习题",
                "db_table": "learning_english_exercise",
            },
        ),
        migrations.CreateModel(
            name="DiagnosisModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                ("description", models.TextField(blank=True, verbose_name="模型描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChineseExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problemsets",
                    models.CharField(default="", max_length=200, verbose_name="习题集ID"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="习题标题")),
                ("content", models.TextField(verbose_name="习题内容")),
                (
                    "question_type",
                    models.CharField(
                        default="single", max_length=10, verbose_name="题型"
                    ),
                ),
                (
                    "option_text",
                    models.CharField(
                        default=None, max_length=1000, verbose_name="选项内容"
                    ),
                ),
                (
                    "answer",
                    models.CharField(default=None, max_length=500, verbose_name="答案"),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[(1, "简单"), (2, "中等"), (3, "困难")], default=2
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="所属科目",
                    ),
                ),
            ],
            options={
                "verbose_name": "语文习题",
                "verbose_name_plural": "语文习题",
                "db_table": "learning_chinese_exercise",
            },
        ),
        migrations.CreateModel(
            name="AnswerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="关联对象ID"
                    ),
                ),
                ("text_answer", models.TextField(blank=True, verbose_name="文本答案")),
                ("is_correct", models.BooleanField(null=True, verbose_name="是否正确")),
                ("time_spent", models.IntegerField(default=0, verbose_name="答题耗时(秒)")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="关联模型",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={"verbose_name": "答题记录", "verbose_name_plural": "答题记录",},
        ),
    ]
